-- ANSWER 테이블에 데이터 삽입
INSERT INTO ANSWER (ANSWER, ANSWER_ID)
VALUES ('답항1', '답항_ID1');

INSERT INTO ANSWER (ANSWER, ANSWER_ID)
VALUES ('답항2', '답항_ID2');

INSERT INTO ANSWER (ANSWER, ANSWER_ID)
VALUES ('답항3', '답항_ID3');

-- PW 테이블에 데이터 삽입
INSERT INTO PW (PW, PW_ID)
VALUES ('비밀번호1', '비밀번호_ID1');

INSERT INTO PW (PW, PW_ID)
VALUES ('비밀번호2', '비밀번호_ID2');

INSERT INTO PW (PW, PW_ID)
VALUES ('비밀번호3', '비밀번호_ID3');

-- QUESTION 테이블에 데이터 삽입
INSERT INTO QUESTION (QUESTION, QUESTION_ID)
VALUES ('문항1', '문항_ID1');

INSERT INTO QUESTION (QUESTION, QUESTION_ID)
VALUES ('문항2', '문항_ID2');

INSERT INTO QUESTION (QUESTION, QUESTION_ID)
VALUES ('문항3', '문항_ID3');

-- USER 테이블에 데이터 삽입
INSERT INTO USER (USER, USER_ID)
VALUES ('설문자1', '설문자_ID1');

INSERT INTO USER (USER, USER_ID)
VALUES ('설문자2', '설문자_ID2');

INSERT INTO USER (USER, USER_ID)
VALUES ('설문자3', '설문자_ID3');

-- SURVEY 테이블에 데이터 삽입
INSERT INTO SURVEY (QUESTION_ID, ANSWER_ID, SURVEY_ID, USER_ID, PW_ID)
VALUES ('문항_ID1', '답항_ID1', '설문_ID1', '설문자_ID1', '비밀번호_ID1');

INSERT INTO SURVEY (QUESTION_ID, ANSWER_ID, SURVEY_ID, USER_ID, PW_ID)
VALUES ('문항_ID2', '답항_ID2', '설문_ID2', '설문자_ID2', '비밀번호_ID2');

INSERT INTO SURVEY (QUESTION_ID, ANSWER_ID, SURVEY_ID, USER_ID, PW_ID)
VALUES ('문항_ID3', '답항_ID3', '설문_ID3', '설문자_ID3', '비밀번호_ID3');
