
CREATE TABLE ANSWER
(
  ANSWER    VARCHAR(500) NOT NULL COMMENT '답항',
  ANSWER_ID VARCHAR(500) NOT NULL COMMENT '답항_ID',
  PRIMARY KEY (ANSWER_ID)
) COMMENT '답항';

CREATE TABLE PW
(
  PW    VARCHAR(50) NOT NULL COMMENT '비밀번호',
  PW_ID VARCHAR(50) NOT NULL COMMENT '비밀번호_ID',
  PRIMARY KEY (PW_ID)
) COMMENT '비밀번호';

CREATE TABLE QNA
(
  QUESTION_ID VARCHAR(500) NOT NULL COMMENT '문항_ID',
  ANSWER_ID   VARCHAR(500) NOT NULL COMMENT '답항_ID',
  QNA_CODE    VARCHAR(500) NOT NULL COMMENT '문답_CODE',
  PRIMARY KEY (QNA_CODE)
) COMMENT '문답';

CREATE TABLE QUESTION
(
  QUESTION    VARCHAR(500) NOT NULL COMMENT '문항',
  QUESTION_ID VARCHAR(500) NOT NULL COMMENT '문항_ID',
  PRIMARY KEY (QUESTION_ID)
) COMMENT '문항';

CREATE TABLE SURVEY
(
  QUESTION_ID VARCHAR(500) NOT NULL COMMENT '문항_id',
  ANSWER_ID   VARCHAR(500) NOT NULL COMMENT '답항_id',
  SURVEY_ID   VARCHAR(500) NOT NULL COMMENT '설문_id',
  USER_ID     VARCHAR(500) NOT NULL COMMENT '설문자_id',
  PW_ID       VARCHAR(50)  NOT NULL COMMENT '비밀번호_ID',
  PRIMARY KEY (SURVEY_ID)
) COMMENT '설문';

CREATE TABLE USER
(
  USER         VARCHAR(500) NOT NULL COMMENT '설문자',
  USER_ID      VARCHAR(500) NOT NULL COMMENT '설문자_ID',
  USER_LOGINID VARCHAR(500) NOT NULL COMMENT '설문자_로그인ID',
  PRIMARY KEY (USER_ID)
) COMMENT '설문자';

CREATE TABLE USER_INFORMATION
(
  PW_ID                 VARCHAR(50)  NOT NULL COMMENT '비밀번호_ID',
  USER_ID               VARCHAR(500) NOT NULL COMMENT '설문자_ID',
  USER_INFORMATION_CODE VARCHAR(500) NOT NULL COMMENT '회원정보_CODE',
  PRIMARY KEY (USER_INFORMATION_CODE)
) COMMENT '회원정보';

ALTER TABLE SURVEY
  ADD CONSTRAINT FK_QUESTION_TO_SURVEY
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTION (QUESTION_ID);

ALTER TABLE SURVEY
  ADD CONSTRAINT FK_ANSWER_TO_SURVEY
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWER (ANSWER_ID);

ALTER TABLE SURVEY
  ADD CONSTRAINT FK_USER_TO_SURVEY
    FOREIGN KEY (USER_ID)
    REFERENCES USER (USER_ID);

ALTER TABLE QNA
  ADD CONSTRAINT FK_QUESTION_TO_QNA
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTION (QUESTION_ID);

ALTER TABLE QNA
  ADD CONSTRAINT FK_ANSWER_TO_QNA
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWER (ANSWER_ID);

ALTER TABLE SURVEY
  ADD CONSTRAINT FK_PW_TO_SURVEY
    FOREIGN KEY (PW_ID)
    REFERENCES PW (PW_ID);

ALTER TABLE USER_INFORMATION
  ADD CONSTRAINT FK_PW_TO_USER_INFORMATION
    FOREIGN KEY (PW_ID)
    REFERENCES PW (PW_ID);

ALTER TABLE USER_INFORMATION
  ADD CONSTRAINT FK_USER_TO_USER_INFORMATION
    FOREIGN KEY (USER_ID)
    REFERENCES USER (USER_ID);
